name: "Terraform"
on: 
  push: 
     branches:
        - main
jobs:
  terraform:
     name: "Terraform"
     runs_on: "ubuntu-latest"
     env:
       AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
       AWS_SECRET_ACCESS_KEY_ID: ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
     default:
         run:
           working-directory: src
     steps:
        - name: Checkout
          uses: actions/checkout@v2
       
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform-version: 1.9.4
            terraform-wrapper: false
        
        - name:  Terraform Format
          id: fmt
          run: terraform fmt -check 
        
        - name: Terraform Init
          id: init
          run: terraform init

        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color
              